$b64 = [IO.File]::ReadAllText("$PSScriptRoot\seedesktop_cleanup_b64.txt").Trim()
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// Generated by misc/gen_cleanup_dart.ps1 — do not edit by hand.')
[void]$sb.AppendLine('// ignore_for_file: lines_longer_than_80_chars')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('library seedesktop_system_cleanup_ps1;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('/// SeeDesktop — system cleanup with WinForms GUI (STA child process).')
[void]$sb.AppendLine('const String kPsSeeDesktopSystemCleanupGui =')
[void]$sb.Append('    r''& { $e=''')
[void]$sb.Append($b64)
[void]$sb.AppendLine('''; Start-Process (Join-Path $PSHOME ''powershell.exe'') -ArgumentList ''-NoProfile'',''-STA'',''-WindowStyle'',''Normal'',''-EncodedCommand'',$e -Wait }'';')
$out = Join-Path $PSScriptRoot '..\flutter\lib\desktop\pages\seedesktop_system_cleanup_ps1.dart'
[IO.File]::WriteAllText($out, $sb.ToString(), [Text.UTF8Encoding]::new($false))
Write-Host "Wrote $out length=$($sb.Length)"
