#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/seedesktop/seedesktop /usr/bin/seedesktop

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/seedesktop.service ]; then
			rm /etc/systemd/system/seedesktop.service /usr/lib/systemd/system/seedesktop.service /usr/lib/systemd/user/seedesktop.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/seedesktop/files/systemd/seedesktop.service /usr/lib/systemd/system/seedesktop.service
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/seedesktop.service
		fi
		systemctl daemon-reload
		systemctl enable seedesktop
		systemctl start seedesktop
	fi
fi
