#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		rm -f /usr/bin/seedesktop
		
		if [ "systemd" == "${INITSYS}" ]; then

			systemctl stop seedesktop || true
			systemctl disable seedesktop || true
			rm /etc/systemd/system/seedesktop.service /usr/lib/systemd/system/seedesktop.service || true
			
			serverUser=$(ps -ef | grep -E 'seedesktop +--server' | grep -v 'sudo ' | awk '{print $1}' | head -1)
			if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
			then
				systemctl --machine=${serverUser}@.host --user stop seedesktop >/dev/null 2>&1 || true
			fi
			rm /usr/lib/systemd/user/seedesktop.service >/dev/null 2>&1 || true
		fi
        ;;
esac

exit 0
